# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0fdeaffcb460abea936f4515fc0a8e5d0cd653cddd25e66991e9c5f8dadc95eb6c5aaf864362a771e14c0acace14ca7f90793ebdc4e4276642aff2ff7a92d06

test:
  secret_key_base: ce371f03907d05f8e7bcf4b78a6980c843e9393be5d17a0df607671b8af2d2a599a5a6d766c3f7a2c4b5493b51726cc91255264ceb8fb2dca0378f6d4ffebe4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
